# Coolify One-Click Install for Pelican Game Panel and Wings
services:
  panel:
    image: ghcr.io/pelican-dev/wings:main
    restart: always
    volumes:
      - "/srv/pelican/var/:/app/var/"
      - "/srv/pelican/nginx/:/etc/nginx/http.d/"
      - "/srv/pelican/certs/:/etc/letsencrypt/"
      - "/srv/pelican/logs/:/app/storage/logs"
    environment:
      APP_URL: "http://${PANEL_URL}"
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      APP_TIMEZONE: ${TIMEZONE}
      APP_SERVICE_AUTHOR: "noreply@example.com"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: ${REDIS_HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_DRIVER: ${MAIL_DRIVER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      PANEL_URL: ${PANEL_URL}
  wings:
    image: ghcr.io/pelican/wings:latest
    restart: always
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pelican
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pelican/:/etc/pelican/"
      - "/var/lib/pelican/:/var/lib/pelican/"
      - "/var/log/pelican/:/var/log/pelican/"
      - "/tmp/pelican/:/tmp/pelican/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
